name:  NodeJs

on:
  push:
    branches: master


permissions: 
   security-events: write
   issues: write
   actions: read
   contents: read

jobs: 
  build:
    runs-on: ubuntu-22.04

    steps: 
      - name:  Checkout Code
        uses:  actions/checkout@v7

      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key:  ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: npm install

      - name: test
        run: npm test
          
      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
             package*

      - name: Deploy
        run: echo "code is deployed"


