name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: BUILD-JOB
    runs-on: ubuntu-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: echo "code build is done"
        
      - name: Test
        run: echo "code is tested!"

      - name: Deploy
        run: echo "my code is deployed

      - name: Rollback
        if: failure()
        echo: "rollback is done"
